version: '3'
services:
  mysql5:
    image: mysql:5.7.22
    container_name: 'mysql5'
    restart: on-failure:10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql/
      - ./config/low-memory-my.cnf:/etc/mysql/my.cnf
    networks:
      - shared-net
networks:
  shared-net:
    external: true

